remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: [Serie de emisi√≥n de luz]
description: [Datos y scripts utilizados en entre la luz y la oscuridad]
